---
image: python:3.10

stages:
  - test

lint:
  stage: test
  script:
    - pip install pre-commit
    - pre-commit run --all-files

test:
  stage: test
  services:
    - postgres:15
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: postgres
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - pip install -r requirements.txt -r requirements-test.txt
    - pytest
