---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # - repo: https://gitlab.com/devopshq/gitlab-ci-linter
  #   rev: v1.0.2
  #   hooks:
  #     - id: gitlab-ci-linter

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.32.1
  #   hooks:
  #     - id: markdownlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # syntax check
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-symlinks
      # whitespaces
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      # scripts/exe
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # credentials leak
      - id: detect-private-key
      # python
      - id: check-docstring-first
      - id: debug-statements
      #- id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: >
          (?x)^(
              .*\.json|
              .*\.html
          )$

  - repo: https://github.com/crate-ci/typos
    rev: v1.12.14
    hooks:
      - id: typos

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.6
    hooks:
      - id: pylint
        additional_dependencies:
          - pylint-django
          - psycopg2-binary
          - django
          - django-stubs-ext
          - djangorestframework
          - drf-yasg[validation]
          - django-filter
          - django-taggit
          - pytest

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit

  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.3.0
  #   hooks:
  #     - id: detect-secrets
  #       exclude_files: html

  # - repo: https://github.com/PyCQA/prospector
  #   rev: 1.7.5
  #   hooks:
  #     - id: prospector
  #       additional_dependencies:
  #         - ".[with_mypy,with_bandit]"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        args: [] # overwrites defaults
        additional_dependencies:
          - psycopg2-binary
          - django
          - djangorestframework
          - drf-yasg[validation]
          - django-filter
          - django-taggit
          - django-stubs[compatible-mypy]
